var CONSTANTS = {
    TIMEOUT_MS: 10000,
    LOADING_DELAY_MS: 300,
    DECK_DRAW_MAX_ATTEMPTS: 100,
    GREEDY_MAX_ATTEMPTS: 50,
    CLOSE_MATCH_THRESHOLD: 2,
    HIGH_DIFFICULTY_THRESHOLD: 12,
    MAX_SKIPPED_SHOWN: 5,
    CUSTOM_MISSION_ID_START: 101,
    MAX_ROUNDS: { 3: 13, 4: 10, 5: 8 },
    TOTAL_CARDS: 40,
    MIN_DIFFICULTY: 1,
    MAX_DIFFICULTY: 50,
    MAX_MODIFIERS_MULTIPLE: 3,
    DISTANCE_WARNING_THRESHOLD: 3,
    STORAGE_KEY: 'crewMissionGeneratorSettings'
};
